version: '1.0'

services:
  app:
    container_name: app
    build: .
    expose:
      - 6666
    networks:
      - portfolio

  nginx:
    container_name: server
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - portfolio

networks:
  portfolio: